spring:
  datasource:
    driver-class-name: "com.mysql.jdbc.Driver"
    url: "jdbc:mysql://14.63.170.200:3306/shinhandb?useUnicode=true&charaterEncoding=utf-8"
    username: "junduff"
    password: "1234"